### ISSUE TITLE
Out of bounds index can be accessed

### ISSUE THREAD

**Issue by yoshuawuyts** [datrs/memory-pager#4]
Ran into this while building hypercore.

![2018-04-24-122511_3840x2160](https://user-images.githubusercontent.com/2467194/39181633-9711331a-47ba-11e8-84d2-a65d7eda3c78.png)

**Comment by ralphtheninja** [comment]
Is this really related to `memory-pager`?

Afaict the panic happens at https://github.com/datrs/hypercore/blob/master/src/bitfield/mod.rs#L183

```rust
let index: usize = self
  .index
  .get_byte(self.iterator.sibling()) // FIXME: out of bounds read
  .into();
```

So there's something fishy around the `.sibling()` code in `flat-tree`.

**Comment by yoshuawuyts** [comment]
@ralphtheninja yeah same, I also suspect there's also something fishy around that in flat-tree; but this was definitely a bug too.
